input_format_version: 0
title: IEA Wind Task 37 Combined Case Study 25 Turbine Farm
description: input file for the 25 turbine wind plant model for IEA Task 37 Combined Case Study
             Template located at <https://github.com/IEAWindTask37/ontology/blob/develop/plant_energy_energy_convolution.yaml>

definitions:
  wind_plant:
    type: object
    description: specific plant design including turbine selection and placement
    properties:
      layout:
        type: array
        items:
          - $ref: "#/definitions/position"
          - $ref: "iea37-335mw.yaml"    # Reference for the .yaml containing turbine attributes.

  position:
    type: array
    items:
      xc: [0.00, 726.00, 363.00, -363.00, -726.00, -363.00, 363.00, 1143.15, 0.00, -1143.15,
           -1143.15, -0.00, 1143.15, 1914.00, 957.00, -957.00, -1914.00, -957.00, 957.00, 2317.09,
           1773.42, 0.00, -1773.42, -2317.09, -2317.09]
      yc: [0.00, 0.00, 628.73, 628.73, 0.00, -628.73, -628.73, 660.00, 1320.00, 660.00, -660.00,
           -1320.00, -660.00, 0.00, 1657.57, 1657.57, 0.00, -1657.57, -1657.57, 959.77, 1773.42,
           2508.00, 1773.42, 959.77, -959.77]
    additionalItems: false
    description: an array of x-coordinates [x0, x1, ...] and y-coordinates [y0, y1, ...] of wind turbine positions in cartesian coordinates
    units: m          

  plant_energy:
    type: object
    description: energy production from simplified Bastankhah Gaussian wake model

    properties:
      wake_model_selection:
        type: algorithm
        description: wake model used to calculate AEP
        items:
          - $ref: "iea37-aepcalc.py"

      wind_resource_selection:
        type: object
        description: specific wind resource used to calculate AEP
        properties:
          type: array
          items:
            - $ref: "iea37-windrose.yaml"       # Reference for the .yaml containing the wind rose

      annual_energy_production:
        type: number
        description: binned and total (default) annual energy production for a wind plant given a layout and binned wind rose
        binned: []
        default: 0.0
        units: MWh